easy_admin:
  site_name: 'NaturaClic Admin'

  edit:
    actions:
      delete:
          name: delete
          type: method
          label: Supprimer
          css_class: 'btn text-danger'
          icon: trash-o
      list:
            name: list
            type: method
            label: Retour à la liste
            css_class: 'btn btn-link pr-0'
            icon: list

  design: 
    assets:
      css:
        - assets/css/easyAdmin.css
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      - '@FOSCKEditor/Form/ckeditor_widget.html.twig'     

  entities:
    
    Especes:
      class: App\Entity\Especes
      
      list:
        fields:
          - { property: 'image', type: 'image', base_path: '%app.path.image%' }
          - { property: 'nomFrancais', label: 'Nom Vernaculaire'}
          - { property: 'nomLatin', label: 'Nom Latin'}
          - { property: 'category', label: 'Catégorie'}
          
      form:
        fields:
          - { property: 'imageFile', type: 'file' }
          - { property: 'nomFrancais', label: 'Nom Vernaculaire'}
          - { property: 'nomLatin', label: 'Nom Latin'}
          - { property: 'description', label: 'description' , type: 'fos_ckeditor' }
          - { property: 'longevite', label: "longevite de l'animal" , type: 'fos_ckeditor' }
          - { property: 'alimentation', label: 'Régime alimentaire' , type: 'fos_ckeditor' }
          - { property: 'repartition', label: 'Répartition' , type: 'fos_ckeditor' }
          - { property: 'habitat', label: 'habitat' , type: 'fos_ckeditor' }
          - { property: 'moeurs', label: 'moeurs / Généralités' , type: 'fos_ckeditor' }
          - { property: 'reproduction', label: 'reproduction / Floraison' , type: 'fos_ckeditor' }
          - { property: 'regne', label: 'Règne'}
          - { property: 'embranchement', label: "embranchement"}
          - { property: 'classeTaxo', label: 'Classe'}
          - { property: 'ordre', label: 'ordre'}
          - { property: 'famille', label: 'famille'}
          - { property: 'statutConservation', label: 'Statut de Conservation'}
          - { property: 'category', label: 'Catégorie'}
          - { property: 'sousCategory', label: 'Sous-Catégorie'}
          - { property: 'pays', label: 'pays', type: 'entity', type_options: { multiple: 'true', by_reference: 'false' }}
              
    category:
      class: App\Entity\Category
      list:
        fields:
          - { property: 'category', label: 'Nombre'}
          - { property: 'name', label: 'famille' }
      form:
        fields:
          - { property: 'name', label: 'famille' }
              
    sousCategory:
      class: App\Entity\SousCategory
      list:
        fields:
          - { property: 'sousCategory', label: 'Nombre'}
          - { property: 'name', label: 'Sous-famille' }
      form:
        fields:
          - { property: 'name', label: 'Sous-famille' }

    pays:
      class: App\Entity\Pays
      list:
        fields:
          - { property: 'name', label: 'pays' }
      form:
        fields:
          - { property: 'name', label: 'pays' }
            
    Photos:
      class: App\Entity\Photos
      list: 
        fields: 
          - { property: 'photo', label: 'Photo', type: 'image', base_path: '%app.path.photo%' }
          - { property: 'nom', label: 'Nom'}
          - { property: 'category', label: 'Catégorie'}
      form:
        fields:
          - { property: 'photoFile', type: 'file', label: 'Photo : ' }
          - { property: 'nom', label: 'Nom vernaculaire : '}
          - { property: 'nomLatin', label: 'Nom latin : '}
          - { property: 'category', label: 'Catégorie : '}
          - { property: 'espece', label: 'Espèce à lier : '}
          - { property: 'pays', label: 'pays', type: 'entity', type_options: { multiple: 'true', by_reference: 'false' }}
                                  
    Article:      
      class: App\Entity\Article

      list:
        fields:
          - { property: 'titre', label: 'Titre' }
          - { property: 'date', label: 'Date de création' }
          - { property: 'image1', label: 'Image associée', type: 'image', base_path: '%app.path.articleImages%' }
      form:
        fields:    
          - { property: 'titre', label: 'Titre' }
          - { property: 'date', label: 'Date de création' }
          - { property: 'paragraphe1', label: 'Paragraphe N°1' , type: 'fos_ckeditor'}
          - { property: 'paragraphe2', label: 'Paragraphe N°2' , type: 'fos_ckeditor'}
          - { property: 'paragraphe3', label: 'Paragraphe N°3' , type: 'fos_ckeditor'}
          - { property: 'paragraphe4', label: 'Paragraphe N°4' , type: 'fos_ckeditor'}
          - { property: 'paragraphe5', label: 'Paragraphe N°5' , type: 'fos_ckeditor'}
          - { property: 'artImg1', label: 'Photo N°1', type: 'file' }
          - { property: 'artImg2', label: 'Photo N°2', type: 'file' }
          - { property: 'artImg3', label: 'Photo N°3', type: 'file' }
          - { property: 'artImg4', label: 'Photo N°4', type: 'file' }
          - { property: 'artImg5', label: 'Photo N°5', type: 'file' }

