vich_uploader:
    db_driver: orm

    mappings:
        image:
            uri_prefix: '%app.path.image%'
            upload_destination: '%kernel.project_dir%/public%app.path.image%'
    
        photo:
            uri_prefix: '%app.path.photo%'
            upload_destination: '%kernel.project_dir%/public%app.path.photo%'
        
        artImg1:
            uri_prefix: '%app.path.articleImages%'
            upload_destination: '%kernel.project_dir%/public%app.path.articleImages%'

        artImg2:
            uri_prefix: '%app.path.articleImages%'
            upload_destination: '%kernel.project_dir%/public%app.path.articleImages%'

        artImg3:
            uri_prefix: '%app.path.articleImages%'
            upload_destination: '%kernel.project_dir%/public%app.path.articleImages%'

        artImg4:
            uri_prefix: '%app.path.articleImages%'
            upload_destination: '%kernel.project_dir%/public%app.path.articleImages%'

        artImg5:
            uri_prefix: '%app.path.articleImages%'
            upload_destination: '%kernel.project_dir%/public%app.path.articleImages%'
        