vich_uploader:
    db_driver: orm

    mappings:
        image:
            uri_prefix: '%app.path.image%'
            upload_destination: '%kernel.project_dir%/public%app.path.image%'
    
        photo:
            uri_prefix: '%app.path.photo%'
            upload_destination: '%kernel.project_dir%/public%app.path.photo%'
        
